name: aws_client
description: High-level APIs for Amazon Web Services (AWS)
version: 0.2.8
author: Istvan Soos <istvan.soos@agilord.com>

homepage: https://github.com/agilord/aws_client

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  crypto: ^2.1.5
  http_client: ^1.3.1
  xml: ^4.5.1

dev_dependencies:
  test: '^1.3.0'
